### ISSUE TITLE
Support for Liferay 7.0/DXP

### ISSUE THREAD

**Issue by slemarchand** [xmlportletfactory/xmlportletfactory#5]
Is there any plan to support Liferay 7.0/DXP in XML Portlet Factory?

**Comment by juangon** [comment]
Hi @slemarchand . We didn't have this in mind, but we may reconsider. Why do you think it would make sense having all the existing Maven artifacts etc for building new OSGI projects?
Thanks!

**Comment by slemarchand** [comment]
Hi @juangon,

It would make sense to support Liferay 7.0/DXP modules generation in XMLPF because, to my knowledge, there is no similar tool for Liferay 7.0/DXP to generate full CRUD (especially including advanced options like asset integration, activities support, excel export, workflow support, chained fields etc).

BLADE tool and Maven artifiacts are very convenient to generate project structure, but neither of them provide a full CRUD generation.

Off course, because Liferay Plugins SDK is now deprecated, the next version of XMLPF Should not rely on Liferay Plugins SDK.

In fact, since such an evolution of XMLPF is not already in progress (as you informed me), I am potentially volunteer to implement this evolution myself.
I wonder if the best approach is to submit a pull request because I do not know if the project is still active. If the project is no longer active, maybe it's better for me to create a new GitHub project? Or maybe are you looking for new maintainers?

What is your feeling ?

**Comment by ciapistess** [comment]
IMHO, the integration with Liferay SDK was even cause of too much 
dependency, especially when generating a complete application and 
automatically deploying it.
Personally, I would vote for a more agile and autonomous tool, able to 
generate pieces of software that could be reused in existent applications.

Andrea

Il 12/04/2017 11.11, Sébastien Le Marchand ha scritto:

**Comment by juangon** [comment]
Hi @slemarchand.

It's fine to keep in this repo, and seems great to me if you volunteer about this new version support! Much appreciated.

As I think it's not trivial at all and some decisions should be made depending on requirements, do you agree if we use some shared document or something to start brainstorming about different aspects like which tool this should be based on (Gradle, Maven..), if using AUI or not, etc. What do you think?

**Comment by slemarchand** [comment]
@juangon,

I think this GitHub issue could be the right place for a such brainstorming. But if your prefer Google Docs, no problem, it also suits me!

For now, my general vision for the very next release of XMLPF is to make the minimal changes needed to support Liferay 7, in order to be able to shortly deliver a usable tool. Later, the following releases could make deeper changes (incrementally).

Thus, in this state of mind:
- the build tool used in projects generated by the next release could be Gradle (because it seems the "most supported" build tool for Liferay 7, as the Plugins SDK was for Liferay 6.2),
- we could continue to use AUI in the next release (and more generally, be as conservative as possible regarding code generation templates)

For the split into modules, I suggest the classic layout `*-service` / `*-api` / `*-web`.

Later, in following releases, we could consider more heavy changes:
- Support for Maven as alternative build tool,
- Support for Metal.js as replacement of AlloyUI,
- Support for Liferay Faces as alternative UI framework,
- Removing support for Liferay 6.x,
- Refactoring XMLPF project (no more Ant dependency, standard directory layout etc),
- Support for smart code generation into existing project (as suggested by @ciapistess),
- ...

**Comment by juangon** [comment]
Hi  @slemarchand. It's funny, as Liferay Faces was one of the things I wanted to implement: https://github.com/xmlportletfactory/xmlportletfactory/issues/2.

I agree in general about what you said for the 1st phase (being conservative and just reuse same structure to generate Gradle projects). gonna send you a shared document with this things so we can track everything.

Thanks very much!

**Comment by slemarchand** [comment]
> Hi @slemarchand. It's funny, as Liferay Faces was one of the things I wanted to implement: #2.

Hi @juangon. It is no coincidence, I mentioned Liferay Faces because I had seen the issue you have submitted ;-)

**Comment by slemarchand** [comment]
[As I commented](https://github.com/xmlportletfactory/xmlportletfactory/pull/6#issuecomment-308552008) in pull request #6 , [Damascus](https://github.com/yasuflatland-lf/damascus) seems to be the natural successor of XMLPF, so this issue could be probably closed.
